### ISSUE TITLE
Log backup information

### ISSUE THREAD

**Issue by geoffreypetri** [geoffreypetri/cyclope#20]
- Database: MongoDB
- Document
```
backup {
  touched: 
  fs: 
  host: 
  name: 
  status: 
  time: 
  weight: 
  created: 
  deleted: 
}
```
